import './globals.css'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body className="antialiased text-slate-900">
        <Navbar />
        {/* TrÆ°á»›c Ä‘Ã¢y: <main className="mx-auto max-w-6xl px-4 py-10">{children}</main> */}
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}


